//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Setup"",
            ""id"": ""03742d69-f2de-4b77-8de9-980e682b0df4"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": []
}");
        // Setup
        m_Setup = asset.FindActionMap("Setup", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Setup
    private readonly InputActionMap m_Setup;
    private List<ISetupActions> m_SetupActionsCallbackInterfaces = new List<ISetupActions>();
    public struct SetupActions
    {
        private @InputActions m_Wrapper;
        public SetupActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_Setup; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SetupActions set) { return set.Get(); }
        public void AddCallbacks(ISetupActions instance)
        {
            if (instance == null || m_Wrapper.m_SetupActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SetupActionsCallbackInterfaces.Add(instance);
        }

        private void UnregisterCallbacks(ISetupActions instance)
        {
        }

        public void RemoveCallbacks(ISetupActions instance)
        {
            if (m_Wrapper.m_SetupActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISetupActions instance)
        {
            foreach (var item in m_Wrapper.m_SetupActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SetupActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SetupActions @Setup => new SetupActions(this);
    public interface ISetupActions
    {
    }
}
